//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgWebMvc.Models
{
    using InstApp.Annotation;
    using System;
    using System.Collections.Generic;

    public partial class division
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public division()
        {
            this.members = new HashSet<member>();
            this.programs = new HashSet<program>();
        }
    
        [FieldAttribute(FieldType =AttributeConstant.TYPE_ID_AI)]
        public int id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_TEXTBOX)]
        public string name { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_TEXTAREA)]
        public string description { get; set; }
      //  [FieldAttribute(FieldType = AttributeConstant.)]
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<program> programs { get; set; }
    }
}
