//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgWebMvc.Models
{
    using InstApp.Annotation;
    using System;
    using System.Collections.Generic;

    public partial class @event
    {
        public @event()
        {
            done = 0;
        }

        [FieldAttribute(FieldType = AttributeConstant.TYPE_ID_AI)]
        public int id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_TEXTBOX)]
        public string name { get; set; }
        [FieldAttribute(Required = true, FieldType = AttributeConstant.TYPE_DROPDOWN, FieldName = "Program Name", ClassRefPropName="program1", ClassReference = "program", ClassAttributeConverter = "name")]
        public int program_id { get; set; }
        public int user_id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_DATE)]
        public System.DateTime date { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_TEXTBOX)]
        public string location { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_NUMBER)]
        public int participant { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_TEXTAREA)]
        public string info { get; set; }
        [FieldAttribute(Required = true, FieldType = AttributeConstant.TYPE_DROPDOWN, Values = new object[] { 0, 1 }, ItemNames = new object[] { "not done", "done" })]
        public int done { get; set; }
        
        
        public virtual program program1 { get; set; }
    }
}
