//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgWebMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class program
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int division_id { get; set; }
    
        public virtual division division { get; set; }
        public virtual @event @event { get; set; }
    }
}
