using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OrgWebMvc.Main.Util
{
    public class Mock
    {
        public static int[] PosId =
          { 16,19,22,25,28,31,34,37,40,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91,94,97,100,103,106,109,112        };
        public static string[] Names =
            { "HARRY","OLIVER" ,"JACK" ,"ALFIE" ,"CHARLIE" ,"THOMAS" ,"JACOB" ,"JAMES" ,"JOSHUA" ,"WILLIAM" ,"ETHAN" ,"GEORGE" ,"RILEY" ,"DANIEL" ,"SAMUEL" ,"NOAH" ,"OSCAR" ,"JOSEPH" ,"MOHAMMED" ,"MAX" ,"DYLAN" ,"MUHAMMAD" ,"ALEXANDER" ,"ARCHIE" ,"BENJAMIN" ,"LUCAS" ,"LEO" ,"HENRY" ,"JAKE" ,"LOGAN" ,"TYLER" ,"JAYDEN" ,"ISAAC" ,"FINLEY" ,"MASON" ,"RYAN" ,"HARRISON" ,"ADAM" ,"LEWIS" ,"EDWARD" ,"LUKE" ,"FREDDIE" ,"MATTHEW" ,"LIAM" ,"ZACHARY" ,"CALLUM" ,"SEBASTIAN" ,"CONNOR" ,"JAMIE" ,"THEO" ,"TOBY" ,"HARVEY" ,"MICHAEL" ,"NATHAN" ,"HARLEY" ,"KAI" ,"DAVID" ,"AARON" ,"ALEX" ,"CHARLES" ,"AIDEN" ,"LEON" ,"MOHAMMAD" ,"LUCA" ,"TOMMY" ,"FINLAY" ,"JENSON" ,"ARTHUR" ,"LOUIS" ,"RHYS" ,"OWEN" ,"REUBEN" ,"OLLIE" ,"LOUIE" ,"GABRIEL" ,"BOBBY" ,"CAMERON" ,"DEXTER" ,"BLAKE" ,"STANLEY" ,"KIAN" ,"EVAN" ,"JUDE" ,"FRANKIE" ,"ELLIOT" ,"HAYDEN" ,"ASHTON" ,"JOEL" ,"CALEB" ,"BAILEY" ,"ELIJAH" ,"TAYLOR" ,"ROBERT" ,"KAYDEN" ,"KYLE" ,"FREDERICK" ,"BEN" ,"REECE" ,"JACKSON" ,"JOHN"};

        public static int[] PosMngId =
         { 1,10,11,12,13,14,15,17,18,20,21,23,24,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111};
        public static string[] MngNames =
    { "AGUSSANTOSO","RAHMAT","INDRA IRAWAN","M. ZIKRULLAH","ARRAHMAN SYAFEBRI","MARQO","OPIANSYAH","MUHAMMAD LEHAN","WISNU SAPUTRA","ZAKARIA SUTOMO","AHMAD FAISAL","SHEH MUHAMMAD","ABDUH","JULIANSYAH EFRIKO","M. FATHUL ISNADI","MUHAMMAD RIDHO","NURSALIM","REZA WIJAYA","MUHAMMAD AKBAR","SONI PERNASUTION","HIDAYAT","WAHYUDI","M. SEPDIANTO","AHMAD YOGA SUGAMA","MARWAN ISKANDAR","EPRIADI","PRANATA AGRIAWAN","ARI NOPITASARI","MUHAMMAD IDRIS","ARIF YULIANTO","KHOIR SAMSI","SAWAL EFFENDI","ANGGI ADITAMA","RIDHO ABRIANTO","IRFAN NAFIAH","ADE WINDO","GERI YOLANDA","DAVID LEONAR","ALAN SAPUTRA","M. FADIL HIDAYAT","HAMDAN SUKRI","MUNAWIR","NANDA SUSANGGA","RAMDONI","DARDIONO","ERWIN EFFENDI","DEDI RIANTO","AHMAD SANJANI","YAYAN HERDIANSYAH","ARDIANSYAH","HERMAN SAPUTRA","PRAMA YUDHA","DONI WINDRA","PAJAR AL QODAR","BONI IRAWAN","RAJESKAN DARMA PUTRAREZA ANDIKA F","ANZAR MUSTAQBAL","RANDI","WENGKI","ARDIAN SYAPUTRA","WILLY HERYAN PRATAMA","MARDIONO","POPIK HIDAYAT","ROBIN SAPUTRA","DODI DARYUSMAN","ELDI HERWANSYAH","RIO FEBRI SEPRIANTO","AHMAD MASYUDI","RACHMAT QUDDUS","JUMARLIS ADE WIJAYA","AHMAD DEDAT","HENDRIANSYAH","AGUSTINUS DWI HANDONO","WENDI FAUZAN SAPUTRA","RIKKI HIMAWAN PUTRA","FERDI SAPUTRA"};

    }
}